[package]
name = "rust-radix-sort"
version = "0.1.0"
authors = ["Omar Saad <omar.saad0705@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
rayon = "1.5"
num_cpus = "1.13"
itertools = "0.8"